import { Email } from './commonInterface';

export const initialEmails: Email[] = [
	{
		id: '1',
		sender: 'Eleanor Pena',
		email: 'eleanorpena@gmail.com',
		subject: 'Subject 1',
		preview: 'Lorem ipsum dolor sit amet consectetur...',
		timestamp: 'May 2, 2024 at 08:45 AM',
		body: 'Full body of the message goes here. Habitasse enim gravida magna...',
	},
	{
		id: '2',
		sender: 'Arlene McCoy',
		email: 'arlenemccoy@gmail.com',
		subject: 'Subject 2',
		preview: 'Lorem ipsum dolor sit amet consectetur...',
		timestamp: 'May 2, 2024 at 08:45 AM',
		body: 'Another message body content goes here.',
	},
	{
		id: '3',
		sender: 'Courtney Henry',
		email: 'courtneyhenry@gmail.com',
		subject: 'Subject 3',
		preview: 'Sed id aliquam neque elementum massa...',
		timestamp: 'May 3, 2024 at 09:30 AM',
		body: 'Full message details for Courtney Henry goes here. Fusce vehicula metus nec neque...',
	},
	{
		id: '4',
		sender: 'Leslie Alexander',
		email: 'lesliealexander@gmail.com',
		subject: 'Subject 4',
		preview: 'Lorem ipsum dolor sit amet, consectetur...',
		timestamp: 'May 4, 2024 at 10:00 AM',
		body: 'The full body content of the email sent by Leslie Alexander goes here. Phasellus dictum nec velit...',
	},
	{
		id: '5',
		sender: 'Ronald Richards',
		email: 'ronaldrichards@gmail.com',
		subject: 'Subject 5',
		preview: 'Aenean in sollicitudin erat, id bibendum libero...',
		timestamp: 'May 5, 2024 at 11:15 AM',
		body: 'Details about the email from Ronald Richards. Nullam placerat fringilla mauris, ut...',
	},
	{
		id: '6',
		sender: 'Floyd Miles',
		email: 'floydmiles@gmail.com',
		subject: 'Subject 6',
		preview: 'Aliquam tincidunt lectus sem...',
		timestamp: 'May 6, 2024 at 12:30 PM',
		body: 'Email content for Floyd Miles. Proin aliquet efficitur lacus, ut lacinia massa...',
	},
	{
		id: '7',
		sender: 'Annette Black',
		email: 'annetteblack@gmail.com',
		subject: 'Subject 7',
		preview: 'Donec tincidunt ligula eget magna vestibulum...',
		timestamp: 'May 7, 2024 at 01:45 PM',
		body: 'The email body for Annette Black. Vestibulum ante ipsum primis in faucibus orci luctus...',
	},
	{
		id: '8',
		sender: 'Jacob Jones',
		email: 'jacobjones@gmail.com',
		subject: 'Subject 8',
		preview: 'Nunc consequat justo non sapien...',
		timestamp: 'May 8, 2024 at 02:00 PM',
		body: 'Complete email body for Jacob Jones. Aenean faucibus nisl non mi...',
	},
	{
		id: '9',
		sender: 'Kristin Watson',
		email: 'kristinwatson@gmail.com',
		subject: 'Subject 9',
		preview: 'Fusce facilisis velit vitae nunc sodales...',
		timestamp: 'May 9, 2024 at 03:15 PM',
		body: 'Details for Kristin Watson’s email. Integer accumsan lorem ut...',
	},
	{
		id: '10',
		sender: 'Darlene Robertson',
		email: 'darlenerobertson@gmail.com',
		subject: 'Subject 10',
		preview: 'Phasellus fermentum suscipit lectus...',
		timestamp: 'May 10, 2024 at 04:30 PM',
		body: 'Email content for Darlene Robertson. Suspendisse euismod dolor at leo interdum...',
	},
];
